spring.application.name=trial
spring.datasource.url=jdbc:h2:file:./database/delivery_weather
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

weather.import.cron=0 15 * * * *

weather.api.url=https://www.ilmateenistus.ee/ilma_andmed/xml/observations.php
weather.api.target-stations=Tallinn-Harku,Tartu-Tõravere,Pärnu
